export const DETAIL_REQUEST = "DETAIL_REQUEST";
export const DETAIL_SUCCESS = "DETAIL_SUCCESS";
export const DETAIL_FAIL = "DETAIL_FAIL";
export const DETAIL_NULL = "DETAIL_NULL";

export const DETAIL_GET_REQUEST = "DETAIL_GET_REQUEST";
export const DETAIL_GET_SUCCESS = "DETAIL_GET_SUCCESS";
export const DETAIL_GET_FAIL = "DETAIL_GET_FAIL";
export const DETAIL_GET_NULL = "DETAIL_GET_NULL";
